---
version: "3"
services:
  redis-db:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    user: "1000:1000"
  flask-app:
    environment:
      - REDIS_IP=redis-db
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.api
    depends_on:
      - redis-db
    image: jakewendling/solar_app:0.1
    ports:
      - 5000:5000
  worker:
    environment:
      - REDIS_IP=redis-db
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.wrk
    depends_on:
      - redis-db
    image: jakewendling/solar_worker:0.1
