---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solar-app-db-pvc
  labels:
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
